[package]
name = "freds"
version = "0.0.0"
edition = "2021"

[features]
default = ["json", "tokio"]
json = ["serde_json"]

[dependencies]
serde_json = {version = "1", optional = true}
tokio = {version = "1", optional = true, features = ["fs", "io-util"]}
